spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-active: 5
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username: root
    password: 111111
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: select 1
  mvc:
    servlet:
      load-on-startup: 1
ribbon:
  eager-load:
    enabled: true
    clients: user-center
  ReadTimeout: 10000
  ConnectionTimeout: 10000

