spring:
  application:
    name: user-center
profiles:
    active:
    - dev
---
spring:
  profiles: test # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效

---
spring:
  profiles: dev  # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效
