spring:
  application:
    name: user-center
profiles:
    active:
    - dev
---
server:
  port: 8088
spring:
  profiles: test # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
---
server:
  port: 7077
spring:
  profiles: dev  # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}