profiles:
    active:
    - dev
---
server:
  port: 7077
spring:
  profiles:
    active: dev
  application:
    name: user-center-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
---
server:
  port: 8088
spring:
  profiles:
    active: test
  application:
    name: user-center-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/