profiles:
    active:
    - dev

---
server:
  port: 8088
spring:
  profiles: test # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效
  application:
    name: user-center-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/


---
server:
  port: 7077
spring:
  profiles: dev  # 此处配置需要注意，不能配成 profiles:active:dev 只能配置成profiles:dev 要不然不生效
  application:
    name: user-center-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/